using System.Net.Http.Headers;
using AV.Household.Commons.Tasks;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Configurations;
using DotNet.Testcontainers.Containers;
using Microsoft.AspNetCore.Mvc.Testing;

namespace AV.Household.WebServer.Testing.Driver;

/// <summary>
///     Base class for microservice tests driver
/// </summary>
/// <typeparam name="TClient">Type of web service client (typically generated by NSwag)</typeparam>
/// <typeparam name="TEntryPoint">Entry point class of web application (typically Program)</typeparam>
public abstract class MicroserviceDriver<TClient, TEntryPoint> : WebApplicationFactory<TEntryPoint>
    where TEntryPoint : class
    where TClient : class
{
    /// <summary>
    ///     Client for microservice
    /// </summary>
    protected readonly AsyncLazy<TClient> Client;

    /// <summary>
    ///     Mongo database container
    /// </summary>
    protected readonly AsyncLazy<MongoDbTestcontainer> Database;

    /// <summary>
    ///     Http client that sends query to microservice
    /// </summary>
    protected readonly AsyncLazy<HttpClient> HttpClient;

    /// <summary>
    ///     Default constructor implementation
    /// </summary>
    /// <exception cref="InvalidOperationException">Throws if can't setup lazy objects</exception>
    protected MicroserviceDriver()
    {
        Database = new AsyncLazy<MongoDbTestcontainer>(async () =>
        {
            var configuration = DatabaseConfiguration ??
                                throw new InvalidOperationException("Database configuration is null.");
            var container = new TestcontainersBuilder<MongoDbTestcontainer>()
                .WithDatabase(configuration)
                .Build();
            await container.StartAsync();
            return container;
        });

        HttpClient = new AsyncLazy<HttpClient>(() => Task.FromResult(CreateClient()));

        Client = new AsyncLazy<TClient>(() => Task.FromResult(
            Activator.CreateInstance(typeof(TClient), HttpClient.GetAwaiter().GetResult()) as TClient
            ?? throw new InvalidOperationException("Can't create web service client. Check its constructor.")));
    }

    /// <summary>
    ///     Returns desired MongoDb configuration
    /// </summary>
    protected abstract MongoDbTestcontainerConfiguration? DatabaseConfiguration { get; }

    /// <summary>
    ///     Set bearer token to access microservice API
    /// </summary>
    /// <param name="bearerToken"></param>
    public async Task SetTokenAsync(string bearerToken)
    {
        if (!string.IsNullOrEmpty(bearerToken))
            (await HttpClient).DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", bearerToken);
    }
}