# This is a basic workflow to help you get started with Actions

name: Validate solution

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:  
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/AV.Household.WebServer.Extensions/AV.Household.WebServer.Extensions.csproj'
      PACKAGE: 'src/AV.Household.WebServer.Extensions/bin/Release/*.nupkg'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setup .NET 6
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        
      # Build project
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
       
      # Authorize in nuget repository        
      - name: Authorize in Github Nuget
        run: dotnet nuget add source --username avmorozov --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AV-Household/index.json"

      # Publish package in nuget repository        
      - name: Publish package in Github Nuget
        run: dotnet nuget push $PACKAGE --source "github"