name: Validate solution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'AV.Household.WebServer.Extensions.sln'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
            
      - name: Authorize in Github Nuget
        run: dotnet nuget add source --username avmorozov --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AV-Household/index.json"

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
